# Ubuntu look: Yaru from Ubuntu 24.04 (GPL-3.0 / CC-BY-SA-4.0) and the Ubuntu font
# (Ubuntu Font Licence 1.0).
STYLE_NAME="Ubuntu"
DEFAULT_VARIANT=light
GTK_THEME_light=Yaru
GTK_THEME_dark=Yaru-dark
ICON_THEME_light=Yaru
ICON_THEME_dark=Yaru-dark
CURSOR_THEME_light=Adwaita
CURSOR_THEME_dark=Adwaita
KVANTUM_THEME_light=KvYaru
KVANTUM_THEME_dark=KvGnomeDark
FONT="Ubuntu 11"
MONO_FONT="Ubuntu Mono 11"
CURSOR_SIZE=24
BUTTON_LAYOUT="menu:minimize,maximize,close"
