#!/usr/bin/env python3
"""Generate lane.c: every AdvSIMD single-structure load/store (LD1-4/ST1-4 to a lane,
LD1R-LD4R) for all element sizes, lane indices, Q, and addressing forms
(no offset, post-index immediate, post-index register), with Rt wrapping past v31.
    python3 gen_lane.py > lane.c"""

SIZES = [("b", 16), ("h", 8), ("s", 4), ("d", 2)]
ARR = {"b": ("8b", "16b"), "h": ("4h", "8h"), "s": ("2s", "4s"), "d": ("1d", "2d")}
EBYTES = {"b": 1, "h": 2, "s": 4, "d": 8}

cases = []  # (name, asm, first_reg, nregs)


def regs(t, n, suffix):
    return "{ " + ", ".join(f"v{(t + i) % 32}.{suffix}" for i in range(n)) + " }"


for n in range(1, 5):
    for sz, lanes in SIZES:
        for lane in range(lanes):
            t = 30 if (lane % 3 == 0 and n > 1) else 20 + n
            for op in ("ld", "st"):
                for mode in ("off", "imm", "reg"):
                    post = {"off": "", "imm": f", #{n * EBYTES[sz]}", "reg": ", x10"}[mode]
                    asm = f"{op}{n} {regs(t, n, sz)}[{lane}], [x9]{post}"
                    cases.append((f"{op}{n}_{sz}{lane}_{mode}", asm, t, n))
    for sz, _ in SIZES:
        for q in (0, 1):
            t = 30 if n > 2 else 24
            for mode in ("off", "imm", "reg"):
                post = {"off": "", "imm": f", #{n * EBYTES[sz]}", "reg": ", x10"}[mode]
                asm = f"ld{n}r {regs(t, n, ARR[sz][q])}, [x9]{post}"
                cases.append((f"ld{n}r_{ARR[sz][q]}_{mode}", asm, t, n))

out = []
out.append('''// GENERATED by gen_lane.py - single-structure lane load/store/replicate conformance.
//   cc -O1 -o lane lane.c && ./lane > native.txt   (same in the guest; diff the output)
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static uint8_t buf[256] __attribute__((aligned(16)));
static uint8_t vin[4][16], vout[4][16];

#define VREGS "v0","v1","v2","v3","v4","v5","v6","v7","v8","v9","v10","v11","v12","v13","v14","v15", \\
    "v16","v17","v18","v19","v20","v21","v22","v23","v24","v25","v26","v27","v28","v29","v30","v31"

static void reset(void) {
    for (int i = 0; i < 256; i++) buf[i] = (uint8_t) (i * 7 + 3);
    for (int r = 0; r < 4; r++) for (int i = 0; i < 16; i++) vin[r][i] = (uint8_t) (0xa0 + r * 16 + i);
}

static void report(const char *name, uint64_t x9, int n) {
    printf("%s x9+%" PRId64, name, (int64_t) (x9 - (uint64_t) (uintptr_t) (buf + 64)));
    for (int r = 0; r < n; r++) {
        printf(" v");
        for (int i = 15; i >= 0; i--) printf("%02x", vout[r][i]);
    }
    uint32_t h = 2166136261u;
    for (int i = 0; i < 256; i++) h = (h ^ buf[i]) * 16777619u;
    printf(" mem=%08x\\n", h);
}
''')

for i, (name, asm, t, n) in enumerate(cases):
    loads = "".join(f'"ldr q{(t + k) % 32}, [%[vin], #{16 * k}]\\n\\t"' for k in range(n))
    stores = "".join(f'"str q{(t + k) % 32}, [%[vout], #{16 * k}]\\n\\t"' for k in range(n))
    out.append(f'''static void t{i}(void) {{
    reset();
    register uint64_t x9 __asm__("x9") = (uint64_t) (uintptr_t) (buf + 64);
    register uint64_t x10 __asm__("x10") = 24;
    __asm__ volatile({loads}"{asm}\\n\\t"{stores}
        : "+r"(x9) : "r"(x10), [vin] "r"(vin), [vout] "r"(vout) : "memory", VREGS);
    report("{name}", x9, {n});
}}''')

out.append("int main(void) {")
for i in range(len(cases)):
    out.append(f"    t{i}();")
out.append("    return 0;\n}")
print("\n".join(out))
