import Observation
import SwiftUI
import UIKit

/// Icons from the guest's per-style icon cache (themes/CONTRACT.md):
/// `/usr/share/ish/icon-cache/<style>/<freedesktop-name>[@2x].png`. The cache is
/// regenerated by `ish-apply-style <style>` in the guest; every lookup falls back to an SF
/// Symbol when the cache or the icon is missing.
@Observable @MainActor
final class DesktopIconStore {
    static let cacheDirectory = "usr/share/ish/icon-cache"

    /// Freedesktop names for the built-in apps.
    static let builtinIconNames: [String: String] = builtinIconCandidates.compactMapValues(\.first)

    /// Icon names tried, in order, for each built-in app; the first is what the app is
    /// asked for, the rest are other packs' spellings.
    static let builtinIconCandidates: [String: [String]] = [
        AppID.terminal: ["utilities-terminal", "org.gnome.Terminal", "terminal"],
        AppID.files: ["system-file-manager", "org.gnome.Nautilus", "file-manager", "folder"],
        AppID.editor: ["accessories-text-editor", "org.gnome.TextEditor", "text-editor", "gedit"],
        AppID.browser: ["web-browser", "firefox", "internet-web-browser"],
        AppID.taskManager: ["utilities-system-monitor", "org.gnome.SystemMonitor", "gnome-system-monitor"],
        AppID.packages: ["system-software-install", "org.gnome.Software", "software-store", "system-software-update"],
        AppID.settings: ["preferences-system", "org.gnome.Settings", "gnome-control-center", "preferences-desktop"],
        WallpapersApp.id: ["preferences-desktop-wallpaper", "wallpaper", "preferences-desktop-background"],
        ThemesApp.id: ["preferences-desktop-theme", "preferences-desktop-color", "applications-graphics",
                       "preferences-desktop-appearance"],
        CalendarApp.id: ["office-calendar", "x-office-calendar", "calendar"],
        LinPadStoreApp.id: ["software-store", "org.gnome.Software", "plasmadiscover", "system-software-install"],
    ]

    /// Icon themes name some apps differently; each list is tried in order.
    static let aliases: [String: [String]] = {
        var table: [String: [String]] = [
            "code": ["vscode", "com.visualstudio.code", "visual-studio-code", "code-oss", "com.visualstudio.code.oss"],
            "code-oss": ["com.visualstudio.code.oss", "vscode", "code", "com.visualstudio.code", "visual-studio-code"],
            "firefox-esr": ["firefox", "org.mozilla.firefox"],
            "thunar": ["org.xfce.thunar", "system-file-manager"],
            "vlc": ["org.videolan.VLC", "multimedia-video-player"],
            "thunderbird": ["org.mozilla.Thunderbird", "mail-client"],
        ]
        let lists = Array(builtinIconCandidates.values) + LinuxFeaturedApp.all.map(\.iconNames)
        for list in lists {
            guard let first = list.first else { continue }
            table[first] = Array(list.dropFirst()) + (table[first] ?? []).filter { !list.contains($0) }
        }
        return table
    }()

    private(set) var style: DesktopStyle
    private(set) var isDark = true
    /// Bumped whenever the cache may have changed, so views showing icons refresh.
    private(set) var generation = 0
    /// Icon packs installed in the guest, for Settings > Icons.
    let packs = IconPackStore()
    @ObservationIgnored private let guestRoot: URL?
    @ObservationIgnored private var images: [String: UIImage] = [:]
    @ObservationIgnored private var missing: Set<String> = []
    @ObservationIgnored private var icons: [String: ThemeIconImage] = [:]
    @ObservationIgnored private var missingIcons: Set<String> = []
    /// First match per candidate list, so a list view asks the disk once per file type.
    @ObservationIgnored private var resolved: [[String]: ThemeIconImage?] = [:]
    @ObservationIgnored private var cacheIndex: IconCacheIndex??
    @ObservationIgnored private var resolvedDirectory: URL?
    @ObservationIgnored private var isWatchingForCache = false
    @ObservationIgnored private var bundledIcons: [String: ThemeIconImage] = [:]
    /// Menu-sized copies (ThemeSymbolIcons.swift), by size and names.
    @ObservationIgnored private var sizedImages: [String: UIImage] = [:]
    /// Image files read since the last reload (tests check scrolling does not read).
    @ObservationIgnored private(set) var fileReads = 0

    /// The store of the desktop on screen, for UIKit menus that have no SwiftUI environment.
    static weak var active: DesktopIconStore?

    init(guestRoot: URL?, style: DesktopStyle) {
        self.guestRoot = guestRoot ?? Self.debugGuestRoot
        self.style = style
        Self.active = self
    }

    func image(named name: String?) -> UIImage? {
        // `Icon=` may be a path or carry an extension; the cache is keyed by the bare name.
        guard let raw = name, case let name = LinuxIconCache.iconName(raw), !name.isEmpty else {
            _ = generation
            return nil
        }
        return icon([name] + (Self.aliases[name] ?? []))?.image
    }

    /// The first of `names` the icon pack has, else the first the bundled default pack has
    /// (Resources/Icons): a decoded image, and whether it is a symbolic (one-colour) icon the
    /// caller should tint. Names are freedesktop icon names in fallback order; nil only when
    /// neither pack has any of them.
    func icon(_ names: [String]) -> ThemeIconImage? {
        _ = generation
        if let hit = resolved[names] { return hit }
        let directory = directory
        let icon = names.lazy.compactMap { self.load($0, in: directory) }.first
            ?? names.lazy.compactMap { self.loadBundled($0) }.first
        // Until the guest's cache exists (first boot, a style being rendered) the answer may
        // change, so it is not remembered.
        if directory != nil || guestRoot == nil { resolved[names] = .some(icon) }
        return icon
    }

    /// `icon` drawn aspect-fit into a `points` square, template when symbolic.
    func sizedImage(_ icon: ThemeIconImage, names: [String], points: CGFloat) -> UIImage {
        let key = "\(points)|" + names.joined(separator: "|")
        if let image = sizedImages[key] { return image }
        let source = icon.image.size
        let scale = min(points / max(source.width, 1), points / max(source.height, 1))
        let drawn = CGSize(width: source.width * scale, height: source.height * scale)
        let image = UIGraphicsImageRenderer(size: CGSize(width: points, height: points)).image { _ in
            icon.image.draw(in: CGRect(x: (points - drawn.width) / 2, y: (points - drawn.height) / 2,
                                       width: drawn.width, height: drawn.height))
        }
        .withRenderingMode(icon.isSymbolic ? .alwaysTemplate : .alwaysOriginal)
        sizedImages[key] = image
        return image
    }

    private func loadBundled(_ name: String) -> ThemeIconImage? {
        if let icon = bundledIcons[name] { return icon }
        guard let directory = BundledIcons.directory, let entry = BundledIcons.index?.entry(for: name),
              let image = UIImage(contentsOfFile: directory.appendingPathComponent(entry.file2x).path) else { return nil }
        let icon = ThemeIconImage(image: image.preparingForDisplay() ?? image, isSymbolic: entry.isSymbolic)
        bundledIcons[name] = icon
        return icon
    }

    private func load(_ name: String, in directory: URL?) -> ThemeIconImage? {
        if let icon = icons[name] { return icon }
        guard !missingIcons.contains(name), let directory else { return nil }
        var files = ["\(name)@2x.png", "\(name).png"]
        var symbolic = false
        if let index = loadIndex(in: directory) {
            guard let entry = index.entry(for: name) else {
                missingIcons.insert(name)
                return nil
            }
            files = [entry.file2x, entry.file1x]
            symbolic = entry.isSymbolic
        }
        for file in files {
            fileReads += 1
            if let image = UIImage(contentsOfFile: directory.appendingPathComponent(file).path) {
                let icon = ThemeIconImage(image: image.preparingForDisplay() ?? image, isSymbolic: symbolic)
                icons[name] = icon
                return icon
            }
        }
        missingIcons.insert(name)
        return nil
    }

    private func loadIndex(in directory: URL) -> IconCacheIndex? {
        if let cacheIndex { return cacheIndex }
        let index = IconCacheIndex(contentsOf: directory.appendingPathComponent("index.json"))
        cacheIndex = .some(index)
        return index
    }

    /// Whether the guest's themes differ from what the desktop wants; checked against
    /// /usr/share/ish/current-style(.env), which ish-apply-style writes last.
    func needsApply(_ style: DesktopStyle, dark: Bool) async -> Bool {
        guard let guestRoot else { return false }
        let cache = LinuxIconCache(guestRoot: guestRoot)
        guard cache.currentStyle == style.rawValue else { return true }
        let env = (try? String(contentsOf: guestRoot.appendingPathComponent("usr/share/ish/current-style.env"),
                               encoding: .utf8)) ?? ""
        return !env.contains("ISH_STYLE_VARIANT=\(dark ? "dark" : "light")")
    }

    func useCache(for style: DesktopStyle, dark: Bool) {
        self.style = style
        isDark = dark
        reload()
    }

    /// Switches the guest's GTK, Qt and icon themes to `style`, then reloads the icons it
    /// regenerated. Returns false for guests without the theming package, which keep the
    /// SF Symbol fallbacks.
    func apply(_ style: DesktopStyle, dark: Bool, host: any LinuxHost) async -> Bool {
        useCache(for: style, dark: dark)
        let result = await host.run(
            "command -v ish-apply-style >/dev/null 2>&1 && ish-apply-style \(style.rawValue.shellQuoted) \(dark ? "dark" : "light")")
        if result.succeeded { reload() }
        return result.succeeded
    }

    /// An icon file named by a .desktop entry or resolved by the Linux bridge (`iconURL`).
    func image(at url: URL?) -> UIImage? {
        _ = generation
        guard let url else { return nil }
        let key = url.path
        if let image = images[key] { return image }
        guard !missing.contains(key) else { return nil }
        if let image = UIImage(contentsOfFile: key) {
            images[key] = image
            return image
        }
        missing.insert(key)
        return nil
    }

    /// The guest rebuilt the cache under the current style (a new icon pack).
    func cacheChanged() {
        reload()
    }

    private func reload() {
        images.removeAll()
        missing.removeAll()
        icons.removeAll()
        missingIcons.removeAll()
        resolved.removeAll()
        sizedImages.removeAll()
        cacheIndex = nil
        if !isWatchingForCache { resolvedDirectory = nil }
        fileReads = 0
        generation += 1
    }

    /// The style's cache; until the guest has rendered that one (a style it does not know
    /// yet, or a switch in progress), the cache of the style the guest last applied.
    private var directory: URL? {
        if let resolvedDirectory { return resolvedDirectory }
        guard guestRoot != nil, !isWatchingForCache else { return nil }
        let directory = findDirectory()
        if directory == nil { watchForCache() }
        resolvedDirectory = directory
        return directory
    }

    /// Polls (every 2 s) until the guest has written a cache, then redraws the icons.
    private func watchForCache() {
        isWatchingForCache = true
        Task { @MainActor [weak self] in
            while let self, self.isWatchingForCache {
                try? await Task.sleep(for: .seconds(2))
                if let found = self.findDirectory() {
                    self.isWatchingForCache = false
                    self.resolvedDirectory = found
                    self.reload()
                }
            }
        }
    }

    private func findDirectory() -> URL? {
        guestRoot.flatMap { root -> URL? in
            let caches = root.appendingPathComponent(Self.cacheDirectory, isDirectory: true)
            let own = caches.appendingPathComponent(style.rawValue, isDirectory: true)
            if FileManager.default.fileExists(atPath: own.path) { return own }
            guard let current = LinuxIconCache(guestRoot: root).currentStyle else { return nil }
            let fallback = caches.appendingPathComponent(current, isDirectory: true)
            return FileManager.default.fileExists(atPath: fallback.path) ? fallback : nil
        }
    }

    /// `-desktop.iconCacheRoot PATH`: a directory laid out like the guest's "/" whose icon
    /// cache hosts without a guest filesystem (the UX harness) draw from.
    private static var debugGuestRoot: URL? {
        #if DEBUG || DESKTOP_AUTOMATION
        UserDefaults.standard.string(forKey: "desktop.iconCacheRoot").map { URL(fileURLWithPath: $0, isDirectory: true) }
        #else
        nil
        #endif
    }
}

/// An icon from the pack: the decoded image, and whether it is a symbolic icon (a
/// one-colour mask drawn in the surrounding text colour).
struct ThemeIconImage {
    let image: UIImage
    let isSymbolic: Bool
}

/// The cache's index.json (themes/CONTRACT.md): which names the pack resolved and their files.
struct IconCacheIndex {
    struct Entry: Equatable {
        let file1x: String
        let file2x: String
        let isSymbolic: Bool
    }

    private let entries: [String: Entry]
    /// Names the guest could not resolve when it rendered the cache.
    let missing: Set<String>
    /// Entries by file stem: an `Icon=/path/app.png` key is looked up as "app".
    private let byStem: [String: Entry]

    init?(contentsOf url: URL) {
        guard let data = FileManager.default.contents(atPath: url.path),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let icons = json["icons"] as? [String: [String: Any]] else { return nil }
        var entries: [String: Entry] = [:]
        var byStem: [String: Entry] = [:]
        for (name, fields) in icons {
            guard let file1x = fields["1x"] as? String else { continue }
            let entry = Entry(file1x: file1x, file2x: fields["2x"] as? String ?? file1x,
                              isSymbolic: fields["symbolic"] as? Bool ?? false)
            entries[name] = entry
            if name.hasPrefix("/") { byStem[String(file1x.dropLast(".png".count))] = entry }
        }
        self.entries = entries
        self.byStem = byStem
        missing = Set(json["missing"] as? [String] ?? [])
    }

    var names: Set<String> { Set(entries.keys) }

    func entry(for name: String) -> Entry? {
        entries[name] ?? byStem[name]
    }
}

private struct DesktopIconStoreKey: EnvironmentKey {
    static let defaultValue: DesktopIconStore? = nil
}

extension EnvironmentValues {
    var desktopIcons: DesktopIconStore? {
        get { self[DesktopIconStoreKey.self] }
        set { self[DesktopIconStoreKey.self] = newValue }
    }
}

extension DesktopController {
    /// The icon file the Linux bridge resolved for an app, if any.
    func iconURL(forAppID appID: String) -> URL? {
        launcherApps.first { $0.id == appID }?.iconURL
    }

    /// The freedesktop icon name for an app: a built-in's mapped name, or a Linux app's
    /// `Icon=` from its .desktop entry.
    func iconName(forAppID appID: String) -> String? {
        if let name = DesktopIconStore.builtinIconNames[appID] { return name }
        guard appID.hasPrefix(LinuxAppID.prefix) else { return nil }
        let id = String(appID.dropFirst(LinuxAppID.prefix.count))
        if let featured = LinuxFeaturedApp.all.first(where: { $0.id == id }) { return featured.iconNames.first }
        return linux?.applications.first { $0.id == id }?.icon ?? id
    }
}

/// An app's icon from the style's icon pack, or its SF Symbol on an accent tile.
struct AppIcon: View {
    let iconName: String?
    var url: URL? = nil
    let symbol: String
    let size: CGFloat
    @Environment(\.desktopIcons) private var icons

    var body: some View {
        if let image = icons?.image(named: iconName) ?? icons?.image(at: url) {
            Image(uiImage: image)
                .resizable()
                .interpolation(.high)
                .aspectRatio(contentMode: .fit)
                .frame(width: size, height: size)
                .accessibilityHidden(true)
        } else {
            // Only for a name neither the pack nor the bundled default pack has: a plain glyph.
            Image(systemName: symbol)
                .font(.system(size: size * 0.6, weight: .regular))
                .foregroundStyle(.primary)
                .frame(width: size, height: size)
                .accessibilityHidden(true)
        }
    }
}

/// A small inline glyph (title bars, taskbar buttons): the icon pack's image or the symbol.
struct AppGlyph: View {
    let iconName: String?
    var url: URL? = nil
    let symbol: String
    let size: CGFloat
    var tint: Color
    @Environment(\.desktopIcons) private var icons

    var body: some View {
        if let image = icons?.image(named: iconName) ?? icons?.image(at: url) {
            Image(uiImage: image)
                .resizable()
                .interpolation(.high)
                .aspectRatio(contentMode: .fit)
                .frame(width: size + 3, height: size + 3)
                .accessibilityHidden(true)
        } else {
            Image(systemName: symbol)
                .font(.system(size: size, weight: .semibold))
                .foregroundStyle(tint)
                .accessibilityHidden(true)
        }
    }
}

/// The default icon pack bundled with the app (Resources/Icons, Papirus, GPL-3.0; see
/// LICENSE there): pre-rendered like a guest cache (themes/CONTRACT.md) for every name the
/// shell asks for, so a real icon shows before Linux has booted and on hosts without a guest.
/// Regenerate with themes/build-bundled-icons.sh when the guest's name lists change.
enum BundledIcons {
    static let directory: URL? = Bundle.module.url(forResource: "Icons", withExtension: nil)
    static let index: IconCacheIndex? = directory.flatMap { IconCacheIndex(contentsOf: $0.appendingPathComponent("index.json")) }
}
