import Observation
import SwiftUI
import UIKit

/// Icons from the guest's per-style icon cache (themes/CONTRACT.md):
/// `/usr/share/ish/icon-cache/<style>/<freedesktop-name>[@2x].png`. The cache is
/// regenerated by `ish-apply-style <style>` in the guest; every lookup falls back to an SF
/// Symbol when the cache or the icon is missing.
@Observable @MainActor
final class DesktopIconStore {
    static let cacheDirectory = "usr/share/ish/icon-cache"

    /// Freedesktop names for the built-in apps.
    static let builtinIconNames: [String: String] = [
        AppID.terminal: "utilities-terminal",
        AppID.files: "system-file-manager",
        AppID.editor: "accessories-text-editor",
        AppID.browser: "web-browser",
        AppID.taskManager: "utilities-system-monitor",
        AppID.packages: "system-software-install",
        AppID.settings: "preferences-system",
        WallpapersApp.id: "preferences-desktop-wallpaper",
        ThemesApp.id: "preferences-desktop-theme",
    ]

    /// Icon themes name some apps differently; each list is tried in order.
    static let aliases: [String: [String]] = [
        "code": ["vscode", "com.visualstudio.code", "visual-studio-code", "code-oss", "com.visualstudio.code.oss"],
        "code-oss": ["com.visualstudio.code.oss", "vscode", "code", "com.visualstudio.code", "visual-studio-code"],
        "firefox-esr": ["firefox", "org.mozilla.firefox"],
        "thunar": ["org.xfce.thunar", "system-file-manager"],
        "preferences-desktop-theme": ["applications-graphics", "preferences-desktop-color", "preferences-desktop"],
    ]

    private(set) var style: DesktopStyle
    private(set) var isDark = true
    /// Bumped whenever the cache may have changed, so views showing icons refresh.
    private(set) var generation = 0
    /// Icon packs installed in the guest, for Settings > Icons.
    let packs = IconPackStore()
    @ObservationIgnored private let guestRoot: URL?
    @ObservationIgnored private var images: [String: UIImage] = [:]
    @ObservationIgnored private var missing: Set<String> = []

    init(guestRoot: URL?, style: DesktopStyle) {
        self.guestRoot = guestRoot
        self.style = style
    }

    func image(named name: String?) -> UIImage? {
        _ = generation
        // `Icon=` may be a path or carry an extension; the cache is keyed by the bare name.
        guard let raw = name, case let name = LinuxIconCache.iconName(raw), !name.isEmpty,
              let directory else { return nil }
        if let image = images[name] { return image }
        guard !missing.contains(name) else { return nil }
        let names = [name] + (Self.aliases[name] ?? [])
        let urls = names.flatMap { [directory.appendingPathComponent("\($0)@2x.png"), directory.appendingPathComponent("\($0).png")] }
        for url in urls {
            if let image = UIImage(contentsOfFile: url.path) {
                images[name] = image
                return image
            }
        }
        missing.insert(name)
        return nil
    }

    /// Whether the guest's themes differ from what the desktop wants; checked against
    /// /usr/share/ish/current-style(.env), which ish-apply-style writes last.
    func needsApply(_ style: DesktopStyle, dark: Bool) async -> Bool {
        guard let guestRoot else { return false }
        let cache = LinuxIconCache(guestRoot: guestRoot)
        guard cache.currentStyle == style.rawValue else { return true }
        let env = (try? String(contentsOf: guestRoot.appendingPathComponent("usr/share/ish/current-style.env"),
                               encoding: .utf8)) ?? ""
        return !env.contains("ISH_STYLE_VARIANT=\(dark ? "dark" : "light")")
    }

    func useCache(for style: DesktopStyle, dark: Bool) {
        self.style = style
        isDark = dark
        reload()
    }

    /// Switches the guest's GTK, Qt and icon themes to `style`, then reloads the icons it
    /// regenerated. Returns false for guests without the theming package, which keep the
    /// SF Symbol fallbacks.
    func apply(_ style: DesktopStyle, dark: Bool, host: any LinuxHost) async -> Bool {
        useCache(for: style, dark: dark)
        let result = await host.run(
            "command -v ish-apply-style >/dev/null 2>&1 && ish-apply-style \(style.rawValue.shellQuoted) \(dark ? "dark" : "light")")
        if result.succeeded { reload() }
        return result.succeeded
    }

    /// An icon file named by a .desktop entry or resolved by the Linux bridge (`iconURL`).
    func image(at url: URL?) -> UIImage? {
        _ = generation
        guard let url else { return nil }
        let key = url.path
        if let image = images[key] { return image }
        guard !missing.contains(key) else { return nil }
        if let image = UIImage(contentsOfFile: key) {
            images[key] = image
            return image
        }
        missing.insert(key)
        return nil
    }

    /// The guest rebuilt the cache under the current style (a new icon pack).
    func cacheChanged() {
        reload()
    }

    private func reload() {
        images.removeAll()
        missing.removeAll()
        generation += 1
    }

    private var directory: URL? {
        guestRoot?.appendingPathComponent(Self.cacheDirectory, isDirectory: true)
            .appendingPathComponent(style.rawValue, isDirectory: true)
    }
}

private struct DesktopIconStoreKey: EnvironmentKey {
    static let defaultValue: DesktopIconStore? = nil
}

extension EnvironmentValues {
    var desktopIcons: DesktopIconStore? {
        get { self[DesktopIconStoreKey.self] }
        set { self[DesktopIconStoreKey.self] = newValue }
    }
}

extension DesktopController {
    /// The icon file the Linux bridge resolved for an app, if any.
    func iconURL(forAppID appID: String) -> URL? {
        launcherApps.first { $0.id == appID }?.iconURL
    }

    /// The freedesktop icon name for an app: a built-in's mapped name, or a Linux app's
    /// `Icon=` from its .desktop entry.
    func iconName(forAppID appID: String) -> String? {
        if let name = DesktopIconStore.builtinIconNames[appID] { return name }
        guard appID.hasPrefix(LinuxAppID.prefix) else { return nil }
        let id = String(appID.dropFirst(LinuxAppID.prefix.count))
        return linux?.applications.first { $0.id == id }?.icon ?? id
    }
}

/// An app's icon from the style's icon pack, or its SF Symbol on an accent tile.
struct AppIcon: View {
    let iconName: String?
    var url: URL? = nil
    let symbol: String
    let size: CGFloat
    @Environment(\.desktopIcons) private var icons

    var body: some View {
        if let image = icons?.image(named: iconName) ?? icons?.image(at: url) {
            Image(uiImage: image)
                .resizable()
                .interpolation(.high)
                .aspectRatio(contentMode: .fit)
                .frame(width: size, height: size)
                .accessibilityHidden(true)
        } else {
            DesktopAppTile(symbol: symbol, size: size)
        }
    }
}

/// A small inline glyph (title bars, taskbar buttons): the icon pack's image or the symbol.
struct AppGlyph: View {
    let iconName: String?
    var url: URL? = nil
    let symbol: String
    let size: CGFloat
    var tint: Color
    @Environment(\.desktopIcons) private var icons

    var body: some View {
        if let image = icons?.image(named: iconName) ?? icons?.image(at: url) {
            Image(uiImage: image)
                .resizable()
                .interpolation(.high)
                .aspectRatio(contentMode: .fit)
                .frame(width: size + 3, height: size + 3)
                .accessibilityHidden(true)
        } else {
            Image(systemName: symbol)
                .font(.system(size: size, weight: .semibold))
                .foregroundStyle(tint)
                .accessibilityHidden(true)
        }
    }
}
